// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/proto/meat.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeatService_GetMeat_FullMethodName = "/proto.MeatService/GetMeat"
)

// MeatServiceClient is the client API for MeatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeatServiceClient interface {
	GetMeat(ctx context.Context, in *MeatRequest, opts ...grpc.CallOption) (*MeatReply, error)
}

type meatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeatServiceClient(cc grpc.ClientConnInterface) MeatServiceClient {
	return &meatServiceClient{cc}
}

func (c *meatServiceClient) GetMeat(ctx context.Context, in *MeatRequest, opts ...grpc.CallOption) (*MeatReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeatReply)
	err := c.cc.Invoke(ctx, MeatService_GetMeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeatServiceServer is the server API for MeatService service.
// All implementations must embed UnimplementedMeatServiceServer
// for forward compatibility.
type MeatServiceServer interface {
	GetMeat(context.Context, *MeatRequest) (*MeatReply, error)
	mustEmbedUnimplementedMeatServiceServer()
}

// UnimplementedMeatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeatServiceServer struct{}

func (UnimplementedMeatServiceServer) GetMeat(context.Context, *MeatRequest) (*MeatReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeat not implemented")
}
func (UnimplementedMeatServiceServer) mustEmbedUnimplementedMeatServiceServer() {}
func (UnimplementedMeatServiceServer) testEmbeddedByValue()                     {}

// UnsafeMeatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeatServiceServer will
// result in compilation errors.
type UnsafeMeatServiceServer interface {
	mustEmbedUnimplementedMeatServiceServer()
}

func RegisterMeatServiceServer(s grpc.ServiceRegistrar, srv MeatServiceServer) {
	// If the following call pancis, it indicates UnimplementedMeatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeatService_ServiceDesc, srv)
}

func _MeatService_GetMeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeatServiceServer).GetMeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeatService_GetMeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeatServiceServer).GetMeat(ctx, req.(*MeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeatService_ServiceDesc is the grpc.ServiceDesc for MeatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MeatService",
	HandlerType: (*MeatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMeat",
			Handler:    _MeatService_GetMeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/meat.proto",
}
